workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'

install:
  image: node:12
  stage: build
  script:
    - yarn
  cache:
    key: $CI_PROJECT_ID
    policy: pull-push
    paths:
      - "node_modules"

test building:
  image: node:12
  stage: test
  script:
    - CI=false yarn build
  cache:
    key: $CI_PROJECT_ID
    policy: pull
    paths:
      - "node_modules"

run unit tests:
  image: node:12
  stage: test
  script:
    - yarn test
  cache:
    key: $CI_PROJECT_ID
    policy: pull
    paths:
      - "node_modules"

test coverage:
  image: node:12
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit: app/junit.xml
  script:
    - yarn test --colors --coverage --reporters=default --reporters=jest-junit
  cache:
    key: $CI_PROJECT_ID
    policy: pull
    paths:
      - "node_modules"

test firebase functions:
  image: node:12
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit: functions/junit.xml
  script:
    - cd functions
    - yarn
    - json -I -f service-account.json \
      -e "this.type='$TYPE'" \
      -e "this.project_id='$PROJECT_ID'" \
      -e "this.private_key_id='$PRIVATE_KEY_ID'" \
      -e "this.private_key='$PRIVATE_KEY'" \
      -e "this.client_email='$CLIENT_EMAIL'" \
      -e "this.client_id='$CLIENT_ID'" \
      -e "this.auth_uri='$AUTH_URI'" \
      -e "this.token_uri='$TOKEN_URI'" \
      -e "this.auth_provider_x509_cert_url='$AUTH_CERT'" \
      -e "this.client_x509_cert_url='$CLIENT_CERT'" \
    - yarn test --colors --coverage --reporters=default --reporters=jest-junit